### ISSUE TITLE
JSON format output broken in 4.0.1 & 4.0.2

### ISSUE THREAD

**Issue by tfmorris** [git-commit-id/git-commit-id-maven-plugin#517] opened 2020-08-07 19:25 UTC
In 4.0.1 and 4.0.2, using `<format>json</format>` produces an almost empty JSON file which just contains
```
{
  "empty": false
}
```

Using the text properties format works correctly. The exact same configuration works in 4.0.0, but fails in 4.0.1 & 4.0.2. There are no error messages generated.

### Steps to Reproduce

Here's the config file:

```xml
        <configuration>
            <dotGitDirectory>${project.basedir}/.git</dotGitDirectory>
            <verbose>false</verbose>
            <generateGitPropertiesFile>true</generateGitPropertiesFile>
            <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
            <failOnNoGitDirectory>false</failOnNoGitDirectory>
            <failOnUnableToExtractRepoInfo>false</failOnUnableToExtractRepoInfo>
            <format>json</format>
            <gitDescribe>
                <skip>false</skip>
                <always>false</always>
                <dirty>-dirty</dirty>
            </gitDescribe>
            <includeOnlyProperties>
              <includeOnlyProperty>^git.build.(time|version)$</includeOnlyProperty>
              <includeOnlyProperty>^git.branch</includeOnlyProperty>
              <includeOnlyProperty>^git.commit.id.(abbrev|full|describe)$</includeOnlyProperty>
            </includeOnlyProperties>
        </configuration>
```

and the failed build following merging Dependabot's PR for the version upgrade: https://github.com/OpenRefine/OpenRefine/runs/959041175

These steps will reproduce the problem on the dependabot branch which updates the plugin to 4.0.2. The master branch with 4.0.0 produces the correct result.

```bash
git clone https://github.com/OpenRefine/OpenRefine.git
cd OpenRefine/main
git checkout dependabot/maven/pl.project13.maven-git-commit-id-plugin-4.0.2
mvn clean compile
cat webapp/WEB-INF/classes/git.properties
```

### Expected behavior
Correct JSON output generated

### Additional context
For reproducibility please provide the following:

My local versions are below, but it also fails using Github Actions on Ubuntu 18.0.4 LTS with versions [listed here](https://github.com/actions/virtual-environments/blob/ubuntu18/20200802.1/images/linux/Ubuntu1804-README.md).

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/local/share/java/maven3
Java version: 1.8.0_171, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"

```
Feel free to add any other context or screenshots about the bug.

**Comment by TheSnoozer** [comment] 2020-08-07 23:37
Hello,
thank you for reporting and sorry for the inconvenience. I can reproduce the problem with your example and indeed there seems something broken. Will investigate the root cause, for now it seems that serializing the `OrderedProperties` seems to result in the output observed. Perhaps this can get fixed by https://github.com/git-commit-id/git-commit-id-maven-plugin/pull/501.

**Comment by TheSnoozer** [comment] 2020-10-23 15:14
Fixed via https://github.com/git-commit-id/git-commit-id-maven-plugin/pull/501.
A ``mvn clean install && mvn clean package -Dmaven.test.skip=true -Pdemo`` now produces:
```
$ cat ./maven/target/testing.properties

{
    "git.branch": "master",
    "git.branch.something": "MASTER",
    "git.build.time": "2020-10-23T07:12:17-0800",
    "git.build.user.name": "TheSnoozer",
    "git.build.version": "4.0.3-SNAPSHOT",
    "git.closest.tag.commit.count": "30",
    "git.closest.tag.name": "v4.0.2",
    "git.dirty": "true",
    "git.local.branch.ahead": "0",
    "git.local.branch.behind": "0",
    "git.tags": "",
    "git.total.commit.count": "1072"
}
```

**Closed by TheSnoozer** 2020-10-23 15:14 UTC
Labels: bug
