### ISSUE TITLE
Broken 4.9.9 release?

### ISSUE THREAD

**Issue by jebeaudet** [git-commit-id/git-commit-id-maven-plugin#569] opened 2021-07-12 15:08 UTC
### Describe the bug
The release 4.9.9, available on maven central, looks broken. It seems the version was published only as a pom release (https://search.maven.org/artifact/pl.project13.maven/git-commit-id-plugin/4.9.9/maven-plugin vs https://search.maven.org/artifact/pl.project13.maven/git-commit-id-plugin/4.0.5/maven-plugin). 

We use renovate to keep our projects up to date and it detected the 4.9.9 version, bumped it but the PR build fails with : 
```
[ERROR] Plugin pl.project13.maven:git-commit-id-plugin:4.9.9 or one of its dependencies could not be resolved: io.github.git-commit-id:git-commit-id-maven-plugin:jar:4.9.9 was not found in https://internalmavenrepo/artifactory/plugins-release during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of releases has elapsed or updates are forced -> [Help 1]
```

### Steps to Reproduce
The normal 4.0.5 pom configuration breaks with 4.9.9.

### Expected behavior
4.9.9 should work with the same configuration as 4.0.5

Thanks!

**Comment by TheSnoozer** [comment] 2021-07-12 17:18
Hello,
thank you for creating an issue for this.
In fact this is/was on purpose. The 4.9.9-release is a "relocation-pom" which I hope had been done following the steps outlined as in https://maven.apache.org/guides/mini/guide-relocation.html.

This is also highlighted in the link provided:
![image](https://user-images.githubusercontent.com/6849390/125329088-5d26bb00-e345-11eb-8267-03a40b6672f7.png)

For now 4.0.5 is the latest 4.X release and the next one would be 5.0.0 available via:
```xml
<dependency>
    <groupId>io.github.git-commit-id</groupId>
    <artifactId>git-commit-id-maven-plugin</artifactId>
    <version>5.0.0</version>
</dependency>
```

As the version number indicates this is a "breaking" release please consult the release-notes (https://github.com/git-commit-id/git-commit-id-maven-plugin/releases/tag/v5.0.0) for further details what exactly might be "breaking" before switching to the new version.

**Comment by jebeaudet** [comment] 2021-07-12 19:14
Yes I understand and saw the new groupId (I've updated without a hiccup on my end, thx), however, I think you might have missed a step, in the last version with the relocation pom, the jar should be there to make it a valid final version along with the relocation information.

**Comment by TheSnoozer** [comment] 2021-07-12 19:55
Mhh I didn't wanted to publish a jar, or a plugin. All I wanted to publish is the relocation information.

The examples provided in the relocation snippet don't include a jar-file either:
- https://repo.maven.apache.org/maven2/poi/poi/3.1-FINAL/
- https://repo.maven.apache.org/maven2/ant/ant/1.7.0/

The relocation guide speaks of minimalistic poms. Sure I could have also published the jar, but specifically decided against that. A 4.9.9 version in my mind just wants to inform users that the coordinates of the plugin changed. Nothing more. The fact that maven attempts to download the jar is a bug (feel free to follow https://issues.apache.org/jira/browse/MNG-7187).

Certainly there also seem examples that also publish a jar alongside with the relocation:
- https://repo1.maven.org/maven2/commons-configuration/commons-configuration/1.10/
- https://repo1.maven.org/maven2/org/apache/commons/commons-io/1.3.2/
- https://repo1.maven.org/maven2/commons-lang/commons-lang/2.6/

Anyhow, correct or incorrect, blame it on the relocation guide if there is anything missing. Since it's released I can't and won't fix the 4.9.9 release.

Thanks again for starting this, but I'm going ahead and close this since this is "as intended".

**Closed by TheSnoozer** 2021-07-12 19:55 UTC

**Comment by jebeaudet** [comment] 2021-07-12 20:01
Seems like this was reported on renovate as well https://github.com/renovatebot/renovate/issues/5667, it's also part of the issue here, the plugin could detect it's a relocation release but it doesn't.

Not sure about MNG-7187, you're not specifying a <type> so it falls back on jar but I'll let the maven developers the final words.

You could release 4.9.10 with the same relocation and jar but I also understand if you don't want to.

In all cases, thanks for your plugin!



It might not be

**Comment by TheSnoozer** [comment] 2021-07-15 18:23
As mentioned in https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/570 I now have published a plugin again under the new coordinates.
While the 4.9.9 remains a "dummy-release" that should have the same functionallity as 4.0.5 this specific release now should work fine to be used as plugin.

This it is now effectively published in both locations it is available via:
```xml
<groupId>pl.project13.maven</groupId>
<artifactId>git-commit-id-plugin</artifactId>
<version>4.9.9</version>
```
and
```xml
<groupId>io.github.git-commit-id</groupId>
<artifactId>git-commit-id-maven-plugin</artifactId>
<version>4.9.9</version>
```
