### ISSUE TITLE
Uplift plexus-build-api to 1.2.0 with updated groupId

### ISSUE THREAD

**Issue by greatmastermario** [git-commit-id/git-commit-id-maven-plugin#720] opened 2024-03-18 15:15 UTC
### Describe the idea (required)

The plugin is currently using a very old version of plexus-build-api (0.0.7) which is unsupported. The latest version is part of a different groupId and has recent builds. I have validated that the plugin still works with the updated version by adjusting the version locally, so I can open a PR if approved. This should not be a breaking change based on my testing since the code still compiles and runs successfully with no changes.

### Tell us about the expected behaviour (required)

Currently, I am running into build failures due to a CVE in a transitive dependency, so I need to manually override the version of plexus-build-api to get past this CVE. I expect that I should be able to use git-commit-id-maven-plugin without having to override transitive dependencies.

**Comment by TheSnoozer** [comment] 2024-03-18 17:32
Thanks for the ticket, closing as duplicate of https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/717

**Closed by TheSnoozer** 2024-03-18 17:32 UTC
Labels: enhancement, to-triage
