### ISSUE TITLE
REMOVE COMMENT HEADER 

### ISSUE THREAD

**Issue by clembou590** [git-commit-id/git-commit-id-maven-plugin#498] opened 2020-06-13 22:46 UTC
### **here is my configuration:**
```
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>4.0.0</version>
                <configuration>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <useNativeGit>true</useNativeGit>
                    <offline>true</offline>

                    <!-- <excludeProperties> -->
                    <!-- <excludeProperty>git.build.time</excludeProperty> -->
                    <!-- </excludeProperties> -->

                    <includeOnlyProperties>
                        <includeOnlyProperty>git.commit.id</includeOnlyProperty>
                    </includeOnlyProperties>
                </configuration>
            </plugin>

```
### **Here is the result**

```
#Generated by Git-Commit-Id-Plugin
#Sat Jun 13 23:32:11 CEST 2020
git.commit.id=b5a9abcaa86a2c889f4dcb146c69ea7bdb4bfe85
```

I would like to remove the comments with the date because:
1) I do not need it
2) it prevents from performing reproducible build.

--> it would be great if you could add the option : "show/hide header time"

**Comment by joschi** [comment] 2020-06-15 07:34
> I would like to remove the comments with the date because:

Unfortunately this comment is provided by `java.util.Properties` itself and cannot be disabled when using that class.

See also: https://stackoverflow.com/a/24045012

**Comment by TheSnoozer** [comment] 2020-06-16 21:42
This is a duplicate of https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/472. Please follow the linked issue for updates.

**Closed by TheSnoozer** 2020-06-16 21:42 UTC
