### ISSUE TITLE
git.commit.time doesn't honor dateFormatTimeZone when .git folder is not present.

### ISSUE THREAD

**Issue by jrivard** [git-commit-id/git-commit-id-maven-plugin#480] opened 2020-05-07 09:06 UTC
### Describe the bug
When the .git folder is not present and failOnNoGitDirectory=false, git-commit-id-maven-plugin populates a value for git.commit.time parameter of value '20000101000000'.  The format of this value does not honor the dateFormatTimeZone configuration setting if present.

It would be nice if also it was possible to populate a default time for when git is unavailable.

### Additional context
For reproducibility please provide the following:

- the plugin version is being used:
v4.0.0

- the Java-Version is being used (output of ``java -version`` and also include details about oracle-jdk VS open-jdk)
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode)

- the Maven-Version is being used (output of ``mvn --version``)
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-29-generic", arch: "amd64", family: "unix"

- on what Operating System you experience the bug (on Linux run ``lsb_release -a`` or ``cat /etc/*release*``)
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

- in what context maven is being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...)
bash

- how maven is being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``)
mvn package

Feel free to add any other context or screenshots about the bug.

**Comment by TheSnoozer** [comment] 2020-05-09 20:01
Hello,
thank you for creating an issue here.
In general I think the plugin will do pretty much nothing if there is no git folder and failOnNoGitDirectory=false:
```
[INFO] --- git-commit-id-plugin:4.0.0:revision (default) @ submodule-one ---
[INFO] dotGitDirectory is null, aborting execution!
```

Could you perhaps double check if you perhaps have set a fall-back property somewhere?
Also please elaborate why there should be a default (fallback) time if the (git) information could not be extracted? From my perspective I would say if there is no git-dir and a consumer has turned off the failure any result (if any result is available) would mean that the plugin would produce misleading results.

Since I can't reproduce the issue (and think the plugin does nothing), could you perhaps create a reproducer with the debugging-project (https://github.com/TheSnoozer/git-commit-id-debugging/)

Thanks!

**Comment by TheSnoozer** [comment] 2020-07-16 17:43
Feel free to reopen if you can provide a reproducer. Closing for now.

**Closed** 2020-07-16 17:42 UTC
Labels: graveyard, not-a-bug, still open?
